name: build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  build:
    permissions:
      contents: write
      packages: write
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows x64'
            os: windows-latest
            triplet: x64-windows
            suffix: 'windows-win64'
            generator: 'Visual Studio 17 2022'
            arch: '-A x64'
          - name: 'Windows x86'
            os: windows-latest
            triplet: x86-windows
            suffix: 'windows-win32'
            generator: 'Visual Studio 17 2022'
            arch: '-A Win32'
          - name: 'Linux x64'
            os: ubuntu-latest
            triplet: x64-linux
            suffix: 'linux-amd64'
            generator: 'Ninja'
            arch: ''
          - name: 'Mac OSX x64'
            os: macos-latest
            triplet: x64-osx
            suffix: 'osx-amd64'
            generator: 'Ninja'
            arch: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Setup Vcpkg
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            VCPKG_ROOT=C:\\vcpkg
          elif [ "$RUNNER_OS" == "Linux" ]; then
            VCPKG_ROOT=/usr/local/share/vcpkg
          elif [ "$RUNNER_OS" == "macOS" ]; then
            VCPKG_ROOT="$HOME/vcpkg"
          fi
          echo "VCPKG_ROOT=${VCPKG_ROOT}" >> ${GITHUB_ENV}

#      - name: Restore Vcpkg Root Cache
#        id: cache-vcpkg-restore
#        uses: actions/cache/restore@v4
#        env:
#          VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
#        with:
#          path: |
#            ${{ env.VCPKG_ROOT }}
#          key: vcpkg-root-${{ matrix.triplet }}-${{ github.run_id }}
#          restore-keys: |
#            vcpkg-root-${{ matrix.triplet }}

      - name: Configure Vcpkg
        shell: bash
        env:
          VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install vcpkg
            if [[ -d "${{ env.VCPKG_ROOT }}" ]]; then
              pushd "${{ env.VCPKG_ROOT }}"
              git fetch --all
              git reset --hard
              popd
            else
              git clone https://github.com/microsoft/vcpkg "${{ env.VCPKG_ROOT }}"
            fi
          fi
          pushd "${{ env.VCPKG_ROOT }}"
          git fetch origin
          git reset --hard origin/master
          if [ "${{ matrix.triplet }}" == "x64-windows" ] || [ "${{ matrix.triplet }}" == "x86-windows" ]; then
            ./bootstrap-vcpkg.bat
          else
            ./bootstrap-vcpkg.sh
          fi
          popd

      - name: Configure
        shell: bash
        env:
          VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
        run: |
          APP_VERSION=$(git describe --always --tags --abbrev=8 --first-parent --match=v*)
          echo "APP_VERSION=${APP_VERSION}" >> ${GITHUB_ENV}
          echo "App version: ${APP_VERSION}"
          mkdir build
          mkdir install
          if [ "$RUNNER_OS" == "Windows" ]; then
            cmake \
              -B ./build \
              -G "${{ matrix.generator }}" ${{ matrix.arch }} \
              -DCMAKE_INSTALL_PREFIX=./install \
              -DCMAKE_BUILD_TYPE=MinSizeRel \
              -DDOXYBOOK_TESTS=ON \
              -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake \
              .
          else
            cmake \
              -B ./build \
              -G "${{ matrix.generator }}" \
              -DCMAKE_INSTALL_PREFIX=./install \
              -DCMAKE_BUILD_TYPE=MinSizeRel \
              -DDOXYBOOK_TESTS=ON \
              -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} \
              -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake \
              .
          fi

#      - name: Save Vcpkg Root Cache
#        id: cache-vcpkg-save
#        uses: actions/cache/save@v4
#        env:
#          VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
#        with:
#          path: |
#            ${{ env.VCPKG_ROOT }}
#          key: vcpkg-root-${{ matrix.triplet }}-${{ github.run_id }}

      - name: Compile
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            cmake --build ./build --target INSTALL --config MinSizeRel
          else
            cmake --build ./build --target install --config MinSizeRel
          fi

      - name: List runtime dependencies
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            ldd ./install/bin/doxybook2
          elif [ "$RUNNER_OS" == "macOS" ]; then
            otool -L ./install/bin/doxybook2
          fi

      - name: Package
        id: create_artifact
        shell: bash
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
        run: |
          mkdir release
          if [ "$RUNNER_OS" == "Windows" ]; then
            ls ./install
            7z a -r doxybook2.zip ./install/*
          else
            pushd "./install"
            zip -r ./../doxybook2.zip *
            popd
          fi
          NAME=doxybook2-${{ matrix.suffix }}-${{ env.APP_VERSION }}.zip
          mv -v ./doxybook2.zip release/${NAME}
          echo "name=${NAME}" >> $GITHUB_OUTPUT
          echo "path=release/${NAME}" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release-${{ matrix.suffix }}
          path: ./install

      - name: Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: ${{ steps.create_artifact.outputs.path }}
          allowUpdates: true
          artifactContentType: application/zip
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: false
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}

  pages:
    name: Pages
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Dependencies
        shell: bash
        run: |
          sudo apt-get install zip unzip python3-setuptools -y
          mkdir -p ${{ github.workspace }}/public

      - name: Download Node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Download Hugo
        shell: bash
        run: |
          HUGO_VERSION=0.74.1
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          tar xvf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          sudo mv ./hugo /usr/local/bin/hugo
          sudo chmod +x /usr/local/bin/hugo
          hugo version

      - name: Download MkDocs
        shell: bash
        run: |
          sudo python3 -m pip install mkdocs mkdocs-material mkdocs-bootswatch

# Disabled due to VuePress not supporting Vue 3.x
#      - name: Download VuePress
#        shell: bash
#        run: |
#          sudo npm install vuepress vue-template-compiler -g

      - name: Download Honkit CLI
        shell: bash
        run: |
          sudo npm install honkit flat-cache -g

      - name: Download Doxygen
        shell: bash
        run: |
          DOXYGEN_VERSION=1.13.2
          DOXYGEN_VERSION_UNDERSCORE=$(echo "$DOXYGEN_VERSION" | tr '.' '_')
          wget https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION_UNDERSCORE}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          tar -xvzf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          sudo cp ./doxygen-${DOXYGEN_VERSION}/bin/doxygen /usr/local/bin/doxygen
          sudo chmod +x /usr/local/bin/doxygen

      - name: Download Doxybook2 artifact
        uses: actions/download-artifact@v4
        with:
          name: Release-linux-amd64
          path: ${{ runner.temp }}/release

      - name: Install Doxybook2
        shell: bash
        env:
          TMPDIR: ${{ runner.temp }}
        run: |
          sudo cp ${TMPDIR}/release/bin/doxybook2 /usr/local/bin/doxybook2
          sudo chmod +x /usr/local/bin/doxybook2
          /usr/local/bin/doxybook2 --version
          echo "DOXYBOOK2=/usr/local/bin/doxybook2" >> ${GITHUB_ENV}

      - name: Run Doxygen
        shell: bash
        run: |
          cd example
          doxygen

      - name: MkDocs - ReadTheDocs
        shell: bash
        env:
          DOXYBOOK2: ${{ env.DOXYBOOK2 }}
        run: |
          ${DOXYBOOK2} \
            --input ./example/doxygen/xml \
            --output ./example/mkdocs-readthedocs/docs \
            --config ./example/mkdocs-readthedocs/.doxybook/config.json
          cd ./example/mkdocs-readthedocs
          mkdocs build
          cp -r ./site ${{ github.workspace }}/public/mkdocs-readthedocs

      - name: MkDocs - Material
        shell: bash
        env:
          DOXYBOOK2: ${{ env.DOXYBOOK2 }}
        run: |
          ${DOXYBOOK2} \
            --input ./example/doxygen/xml \
            --output ./example/mkdocs-material/docs \
            --config ./example/mkdocs-material/.doxybook/config.json
          cd ./example/mkdocs-material
          mkdocs build
          cp -r ./site ${{ github.workspace }}/public/mkdocs-material

      - name: MkDocs - Bootswatch
        shell: bash
        env:
          DOXYBOOK2: ${{ env.DOXYBOOK2 }}
        run: |
          ${DOXYBOOK2} \
            --input ./example/doxygen/xml \
            --output ./example/mkdocs-bootswatch/docs \
            --config ./example/mkdocs-bootswatch/.doxybook/config.json
          cd ./example/mkdocs-bootswatch
          mkdocs build
          cp -r ./site ${{ github.workspace }}/public/mkdocs-bootswatch

      - name: Hugo - Learn
        shell: bash
        env:
          DOXYBOOK2: ${{ env.DOXYBOOK2 }}
        run: |
          ${DOXYBOOK2} \
            --input ./example/doxygen/xml \
            --output ./example/hugo-learn/content \
            --config ./example/hugo-learn/.doxybook/config.json \
            --templates ./example/hugo-learn/.doxybook/templates
          cd ./example/hugo-learn
          hugo
          cp -r ./public ${{ github.workspace }}/public/hugo-learn

      - name: Hugo - Book
        shell: bash
        env:
          DOXYBOOK2: ${{ env.DOXYBOOK2 }}
        run: |
          ${DOXYBOOK2} \
            --input ./example/doxygen/xml \
            --output ./example/hugo-book/content \
            --config ./example/hugo-book/.doxybook/config.json \
            --templates ./example/hugo-book/.doxybook/templates
          cd ./example/hugo-book
          hugo
          cp -r ./public ${{ github.workspace }}/public/hugo-book

# Disabled due to VuePress not supporting Vue 3.x
#      - name: VuePress - Default
#        shell: bash
#        env:
#          DOXYBOOK2: ${{ env.DOXYBOOK2 }}
#        run: |
#          ${DOXYBOOK2} \
#            --input ./example/doxygen/xml \
#            --output ./example/vuepress \
#            --config ./example/vuepress/.doxybook/config.json
#          cd ./example/vuepress
#          sudo vuepress build
#          cp -r ./.vuepress/dist ${{ github.workspace }}/public/vuepress

# TODO: Usage of sudo to run `honkit` is currently a temporary workaround, needed until honkit
# updates it's flat-cache to more newer version: https://github.com/honkit/honkit/issues/452.
      - name: Honkit - Default
        shell: bash
        env:
          DOXYBOOK2: ${{ env.DOXYBOOK2 }}
        run: |
          ${DOXYBOOK2} \
            --input ./example/doxygen/xml \
            --output ./example/honkit \
            --config ./example/honkit/.doxybook/config.json \
            --summary-input ./example/honkit/SUMMARY.md.tmpl \
            --summary-output ./example/honkit/SUMMARY.md
          cd ./example/honkit
          sudo honkit build
          sudo cp -r ./_book ${{ github.workspace }}/public/honkit

      - name: Additional files
        shell: bash
        run: |
          cp ./example/index.html ${{ github.workspace }}/public/index.html
          cp -r ./example/doxygen/html ${{ github.workspace }}/public/original
          stat ${{ github.workspace }}/public

      - name: Deploy
        if: startsWith(github.ref, 'refs/heads/master')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/public
